name: Autodoc Price Tracker

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:       # allows manual trigger

jobs:
  track-price:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 brotli

      - name: Run price tracker
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: |
          python tracker.py

      - name: Commit updated price history
        run: |
          git config --global user.name "autodoc-tracker-bot"
          git config --global user.email "tracker@example.com"
          git add price_history.txt
          git commit -m "Update price_history.txt" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
